#ifndef _EPS_H_
#define _EPS_H_

/* EPS VALUES */
typedef enum subsystem_EPS {
  EPS_CURRENT_VAL,
  EPS_CURRENT_STATE,
  EPS_VOLTAGE_VAL,
  EPS_VOLTAGE_STATE,
  EPS_TEMPERATURE_VAL,
  EPS_TEMPERATURE_STATE,
  EPS_ALERT,
  EPS_SIZE
};

#endif